### ISSUE TITLE
使用订阅模式，小火箭配置了错误的混淆密码，导致无法正常使用

### ISSUE THREAD

**Issue by dts88** [jonssonyan/h-ui#102]
小火箭根据H-UI订阅链接提供的信息，所配置的混淆密码为salamander，而不是cry_me_a_hui，导致无法正常连接，手动修改后可恢复正常，更新订阅后又恢复为salamander导致连接失败。

目前已知h-ui提供的配置文件，信息应该是正确的。不知道是否各家app对于“obfs”和“obfs-password”的定义有些许不同？有没有解决办法？否则H-UI的订阅模式在小火箭上是不可用的。

> proxies:
>     - name: hysteria2
>       type: hysteria2
>       server: xxxx
>       port: "xxxx"
>       password: xxxx
>       obfs: salamander
>       obfs-password: cry_me_a_hui
>       sni: xxxx
> proxy-groups:
>     - name: PROXY
>       type: select
>       proxies:
>         - hysteria2

**Comment by w9315273** [comment]
默认登陆用户和密码是什么？ docker log没有任何关于登陆密码的信息
```
services:
  Hy2:
    image: jonssonyan/h-ui:latest
    container_name: Hy2
    networks:
      Hy2:
        ipv4_address: 172.20.0.2
    volumes:
      - .h-ui/bin:/h-ui/bin
      - ./h-ui/data:/h-ui/data
      - ./h-ui/export:/h-ui/export
      - ./h-ui/logs:/h-ui/logs
    restart: unless-stopped
networks:
  Hy2:
    external: true
```
